name: 'Acsign'

on:
  push:
  schedule:
    - cron: '2 16 * * *' # 北京时间凌晨0点

jobs:
  acsign:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'

      - name: 'Sign'
        env:
          ACSIGN_USERNAME: ${{ secrets.ACSIGN_USERNAME }}
          ACSIGN_PASSWORD: ${{ secrets.ACSIGN_PASSWORD }}
        run: php run.php
